export const uniAchievementData = [
  {
    id: "000",
    width: 500,
    height: 400,
    image: "/media/uni/uniachieve0.jpg",
    title: "Academic AeroSpace magazine called ASPAD [2020]",
    desc: "I have participated in producing an academic aerospace magazine as writer and editor and this is the picture of our first magazine",
  },
  {
    id: "001",
    width: 500,
    height: 500,
    image: "/media/uni/uniachieve1.jpg",
    width2: 1000,
    height2: 700,
    image2: "/media/uni/uniachieve1_2.jpg",
    title: "Participating in holding academic competition [2019]",
    desc: "This is one of my precious achievement which has been given to me as a member of executive staff at holding solidworks competition at KNTU university",
  },
  {
    id: "002",
    width: 1400,
    height: 900,
    image: "/media/uni/uniachieve3.jpg",
    title:
      "Teaching English Language - Caspian English Language Academy [2019]",
    desc: "This is my TTC(Teacher Training Course) certificate for learning how to teach English language from Caspian English Language Academy under the Ministry of Education",
  },
  {
    id: "003",
    width: 500,
    height: 700,
    image: "/media/uni/uniachieve4.jpg",
    title: "Teaching English Language - SPEAKON LANGUAGE INSTITUTE [2019]",
    desc: "This is my TTC(Teacher Training Course) certificate for learning how to teach English language from SPEAKON LANGUAGE INSTITUTE",
  },
  {
    id: "004",
    width: 1400,
    height: 900,
    image: "/media/uni/uniachieve2.jpg",
    width2: 1000,
    height2: 700,
    image2: "/media/uni/uniachieve2_2.jpg",
    poster: "media/uni/poster2.jpg",
    video: "/media/uni/uniachieve2_1.mp4",
    title: "Working on a new drone [2018]",
    desc: " This certificate has given to me for working on a vertical flight drone(VTOL) as a member of manufacture team at KNTU university",
  },
  {
    id: "005",
    width: 1300,
    height: 900,
    image: "/media/uni/uniachieve5.jpg",
    title: "Graduation in Learning English language [2018]",
    desc: "This is my graduation certificate in learning English from ILI(Iran Language Institute)",
  },
];

export const sportAchievementData = [
  {
    id: "00",
    width: 1400,
    height: 900,
    image: "/media/sport/sportachieve0.jpg",
    title: "Participating in poomsae tutorial courses [2020]",
    desc: "I have participated in creating video of poomsae tecniques beside the grand master of Taekwondo Mr.Dastjerdi",
  },
  {
    id: "000",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve1.jpg",
    title: "Dan 4 certificate [2020]",
    desc: "certificate for Taekwondo black belt Dan4",
  },
  {
    id: "001",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve2.jpg",
    width2: 1000,
    height2: 600,
    image2: "/media/sport/sportachieve2_2.jpg",
    title: "Southwest Poomsae Championship verdict [2019]",
    desc: "First place in the Southwest Poomsae Championship ",
  },
  {
    id: "002",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve3.jpg",
    title: "Tehran Hanmadang league Championship verdict [2019]",
    desc: "Third place in the first Hanmadang Women's League of Tehran province in the standard poomsae section",
  },
  {
    id: "003",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve4.jpg",
    title: "Dan 3 certificate [2017]",
    desc: " certificate for Taekwondo  black belt Dan3",
  },
  {
    id: "004",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve5.jpg",
    title: "Freestyle poomsae competitions Championship verdict [2016]",
    desc: " First place in freestyle poomsae competitions",
  },
  {
    id: "005",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve9.jpg",
    width2: 500,
    height2: 700,
    image2: "/media/sport/sportachieve9_2.jpg",
    title: "Dan 2 certificate [2016]",
    desc: " International and National certificates for Taekwondo black belt Dan2 from Kukkiwon at Korea and Iran respectively",
  },
  {
    id: "006",
    width: 1400,
    height: 900,
    image: "/media/sport/sportachieve8.jpg",
    title: "Women's Gyeorugi competition championship verdict [2015]",
    desc: " Second place in the women's Gyeorugi competition",
  },
  {
    id: "007",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve6.jpg",
    width2: 500,
    height2: 700,
    image2: "/media/sport/sportachieve6_2.jpg",
    title:
      "Hanmadang Nupi-Apchagi and Hanmadang individual Poomsae Championship verdict [2015]",
    desc: " Second place in the Hanmadang Nupi-Apchagi competition and Third place in the Hanmadang individual Poomsae competition",
  },
  {
    id: "008",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve10.jpg",
    title: "Gyeorugi Junior Freestyle competition championship verdict [2015]",
    desc: " Second place in the Gyeorugi Junior Freestyle Championship",
  },
  {
    id: "009",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve12.jpg",
    width2: 500,
    height2: 700,
    image2: "/media/sport/sportachieve12_2.jpg",
    title: "Dan 1 certificate [2015]",
    desc: " International and National certificates for Taekwondo black belt Dan1 from Kukkiwon at Korea and Iran respectively",
  },
  {
    id: "010",
    width: 500,
    height: 700,
    image: "/media/sport/sportachieve13.jpg",
    title: "Cultural and sport festival championship verdict [2014]",
    desc: " Third place in cultural and sport festival",
  },
  {
    id: "011",
    width: 1400,
    height: 900,
    image: "/media/sport/sportachieve15.jpg",
    title: "Victory Days Sport Festival championship verdict [2013]",
    desc: " Third place in the Victory Days Sport Festival",
  },
  {
    id: "012",
    width: 1400,
    height: 900,
    image: "/media/sport/sportachieve16.jpg",
    title: "Gyeorugi championship verdict [2012]",
    desc: " Second place in the Gyeorugi competition",
  },
  {
    id: "013",
    width: 500,
    height: 500,
    image: "/media/sport/sportachieve17.jpg",
    title: "swimmig competitions [2004]",
    desc: " These are two medals for two inter-club competitions which I have participated when I was 5 years old!",
  },
];

export const artAchievementData = [
  {
    id: "001",
    width: 1400,
    height: 1000,
    image: "/media/art/artachieve1.jpg",
    width2: 500,
    height2: 700,
    image2: "/media/art/artachieve1_2.jpg",
    title: "Daf festival of Seraj Library [2020]",
    desc: "This is an art certificate for a Turkish festival of Daf at Seraj Library at Tehran which I have participated ",
  },
  {
    id: "002",
    width: 1400,
    height: 800,
    image: "/media/art/artachieve2.jpg",
    title: "Nowruz of 1399 (new year of Iranian culture) [2020]",
    desc: "Every year, at Nowruz, my mother and me playing Daf for welcoming the new year and Spring",
  },
  {
    id: "003",
    width: 1400,
    height: 800,
    image: "/media/art/artachieve3.jpg",
    width2: 500,
    height2: 700,
    image2: "/media/art/artachieve3_2.jpg",
    title: "Daf festival of Ferdos cultural center at Tehran [2019]",
    desc: "These are our pictures before we go to stage. This festival was held in Ferdos cultural center at Summer.",
  },
  {
    id: "004",
    width: 1400,
    height: 700,
    image: "/media/art/artachieve4.jpg",
    width2: 1000,
    height2: 700,
    image2: "/media/art/artachieve4_2.jpg",
    title: "Daf festival of International Exhibition [2019]",
    desc: "Just before we go to stage. This festival was held in International Exhibition at Winter.",
  },
  {
    id: "005",
    width: 1400,
    height: 800,
    image: "/media/art/artachieve5.jpg",
    width2: 1100,
    height2: 700,
    image2: "/media/art/artachieve5_2.jpg",
    title:
      "Daf Festival at Tehran Pardis Theater in Khavaran Cultural Center [2019]",
    desc: "This festival has been held to respect of a grand Turk musician at winter. My mother, my auntie and me have participated in it.",
  },
];
